apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-nginx-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

    server {
        listen 80;
        server_tokens off;

        gzip on;
        gzip_comp_level 9;
        gzip_types
            application/javascript
            application/rss+xml
            application/json
            application/x-javascript
            application/xml
            image/svg+xml
            text/css
            text/javascript
            text/js
            text/xml
            text/plain
        ;

        if (-f /var/nginx-maintenance) {
            return 503;
            break;
        }

        error_page 503 @maintenance;

        location @maintenance {
            rewrite ^(.*)$ /maintenance.html;
        }

        location /scripts/configs/config.json {
            alias /opnd/config.json;
            expires 4h;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;

            try_files $uri $uri/ /index.html;

            location = /index.html {
                expires -1;
            }

            location ~ /(css|fonts|images|scripts)$ {
                expires 7d;
            }

            location = /login_completed/ {
                return 200 'Authentication is pending.';
                add_header Content-Type text/plain;
            }

            location = /login_failed/ {
                return 401 'Authentication has failed.';
                add_header Content-Type text/plain;
            }
        }

        {{ if .Values.waldur.whitelabeling.loginLogoPath }}
        location /images/login_logo.png {
          alias /var/www/waldur/icons/login_logo.png;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.sidebarLogoPath }}
        location /images/sidebar_logo.png {
          alias /var/www/waldur/icons/sidebar_logo.png;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.poweredByLogoPath }}
        location /images/poweredby_logo.png {
          alias /var/www/waldur/icons/poweredby_logo.png;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.faviconPath }}
        location /images/favicon.ico {
          alias /var/www/waldur/icons/favicon.ico;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.heroImagePath }}
        location /images/hero_image.jpg {
          alias /var/www/waldur/icons/hero_image.jpg;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.tosHtmlPath }}
        location /views/tos/index.html {
          alias /var/www/waldur/files/tos.html;
        }
        {{ end }}

        {{ if .Values.waldur.whitelabeling.privacyHtmlPath }}
        location /views/policy/privacy.html {
          alias /var/www/waldur/files/privacy.html;
        }
        location /views/policy/privacy-full.html {
          alias /var/www/waldur/files/privacy-full.html;
        }
        {{ end }}
      }
    }
