apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-worker
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  {{ if .Values.extraReplicas.celery }}
  replicas: {{ add .Values.replicaCount .Values.extraReplicas.celery }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: waldur-mastermind-worker
  template:
    metadata:
      labels:
        app: waldur-mastermind-worker
    spec:
      containers:
        - name: waldur-mastermind-worker
          image: opennode/waldur-mastermind:{{ .Values.waldur.imageTag }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          args:
            - "worker"
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery inspect -q -A waldur_core.server -d celery@$HOSTNAME ping"
            initialDelaySeconds: 15
            periodSeconds: 25
            timeoutSeconds: 20
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery inspect -q -A waldur_core.server -d celery@$HOSTNAME ping"
            initialDelaySeconds: 20
            periodSeconds: 25
            timeoutSeconds: 20
          env:
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          - name: POSTGRESQL_HOST
            value: {{ template "waldur.postgresql.host" . }}
          - name: POSTGRESQL_PORT
            value: {{ template "waldur.postgresql.port" . }}
          - name: POSTGRESQL_USER
            value: {{ template "waldur.postgresql.user" . }}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "waldur.postgresql.secret" . }}
                key: {{ template "waldur.postgresql.secret.passwordKey" . }}
          - name: POSTGRESQL_NAME
            value: {{ template "waldur.postgresql.dbname" . }}
          - name: LOGGING_LOG_FILE
            value: "/var/log/waldur/core.log"
          - name: EVENTS_LOG_FILE
            value: "/var/log/waldur/events.log"
          {{ if .Values.waldur.sentryDSN }}
          - name: SENTRY_DSN
            value: {{ .Values.waldur.sentryDSN | quote }}
          {{ end }}
          resources:
            {{ if .Values.hpa.celery.enabled }}
            {{- toYaml .Values.hpa.celery.workerResources | nindent 12 }}
            {{ else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{ end }}
          volumeMounts:
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
        {{ if .Values.logManagement.enabled }}
            - name: waldur-log
              mountPath: /var/log/waldur
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.11.0-debian-elasticsearch7-1.0
          imagePullPolicy: IfNotPresent
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.logManagement.elasticHost | quote }}
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.logManagement.elasticPort | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.logManagement.elasticProtocol | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: waldur-log
              mountPath: /var/log/waldur
            - name: fluentd-conf
              mountPath: /fluentd/etc
        {{ end }}
      volumes:
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      {{ if .Values.logManagement.enabled }}
      - name: waldur-log
        emptyDir: {}
      - name: fluentd-conf
        configMap:
          name: fluentd-config
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
